#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🧪 Running tests..."
pnpm test || exit 1

echo "📝 Checking types..."
pnpm test:types || exit 1

echo "📦 Checking bundle size..."
pnpm size || exit 1
